spring:
  application:
    name: micro-service-manager-service

server:
  port: 8001



eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone : http://localhost:8000/eureka/
    registry-fetch-interval-seconds: 30
    initial-instance-info-replication-interval-seconds: 40
